apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      automountServiceAccountToken: false
      containers:
        - name: notification
          envFrom:
            - configMapRef:
                name: notification-service-config
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          image: ghcr.io/soldevlife-assesment-2024-s1/notification-service:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
